service: service-graph
provider:
    name: aws
    runtime: nodejs14.x
    region: us-west-1
functions:
    graphql:
        # this is formatted as <FILENAME>.<HANDLER>
        handler: src/graph.graphqlHandler
        events:
            - http:
                  path: /
                  method: post
                  cors: true
            - http:
                  path: /
                  method: get
                  cors: true

custom:
    webpack:
        webpackConfig: ../../webpack.sls.ts
    memory:
        prd: 1536
        other: 1024 # default lambda memorySize
    prune:
        automatic: true
        number: 5

plugins:
    - serverless-webpack
